# Production Profile
spring.config.activate.on-profile=prod

# Production Server
server.port=8080

# Disable H2 Console in production
spring.h2.console.enabled=false

# Logging
logging.level.com.wildlife.backend=INFO
spring.jpa.show-sql=false

